### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [sgl0v/SCrypto#1]
Now that Xcode 8 is out, SCrypto doesn't work anymore

**Comment by Eke** [comment]
@lfarah i made PR for this, please see #2

**Comment by CandidateTom** [comment]
As of this moment, the version in the cocapods repo is 1.0.2, can you update?

**Comment by Eke** [comment]
@CandidateTom you can point to master branch from pod file before it gets updated

**Comment by sgl0v** [comment]
Pushed v2.0.0 to Cocoapods.
