### ISSUE TITLE
'SCrypto', '~> 2.0.0' doesn't exist in cocoapods's spec repo

### ISSUE THREAD

**Issue by nebiros** [sgl0v/SCrypto#3]
`'SCrypto', '~> 2.0.0'` doesn't exist in cocoapods's spec repo, latest version seems to be: `1.0.2`, `.//d/0/3/SCrypto/1.0.2/SCrypto.podspec.json`

**Comment by sgl0v** [comment]
Done. Had some issues with pushing v2.0.0 to Cocoapods previously.
